import 'package:flutter/material.dart';
import 'dart:io';
import '../../data/repositories/feed_repository.dart';
import '../../data/models/feed_model.dart';
import '../../../../core/services/supabase_service.dart';

class CreatePostViewModel extends ChangeNotifier {
  final FeedRepository repository;
  
  CreatePostViewModel({required this.repository});
  
  File? _selectedImage;
  List<String> _selectedTags = [];
  bool _isLoading = false;
  String? _errorMessage;

  File? get selectedImage => _selectedImage;
  List<String> get selectedTags => _selectedTags;
  bool get isLoading => _isLoading;
  String? get errorMessage => _errorMessage;

  void setImage(File? image) {
    _selectedImage = image;
    notifyListeners();
  }

  void setTags(List<String> tags) {
    _selectedTags = tags;
    notifyListeners();
  }

  void toggleTag(String tag) {
    if (_selectedTags.contains(tag)) {
      _selectedTags.remove(tag);
    } else {
      _selectedTags.add(tag);
    }
    notifyListeners();
  }

  void removeImage() {
    _selectedImage = null;
    notifyListeners();
  }

  Future<bool> createPost({
    required String title,
    required String content,
  }) async {
    _isLoading = true;
    _errorMessage = null;
    notifyListeners();

    try {
      final user = SupabaseService.client.auth.currentUser;
      if (user == null) {
        throw Exception('User not authenticated');
      }

      String? imageUrl;
      
      // Upload image through repository
      if (_selectedImage != null) {
        imageUrl = await repository.uploadPostImage(_selectedImage!, user.id);
      }

      // Create post through repository
      final post = FeedPost(
        id: '', // Will be generated by database
        title: title,
        content: content,
        userId: user.id,
        imageUrl: imageUrl,
        authorName: '', // Will be populated from JOIN
        tags: _selectedTags,
        createdAt: DateTime.now(),
      );

      await repository.createPost(post);

      print('✅ Post created successfully , yes!');
      _selectedImage = null;
      _selectedTags = [];
      return true;
    } catch (e) {
      print('❌ Error creating post: $e');
      _errorMessage = e.toString();
      return false;
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }
}