// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASXCv9PEiuopdAjKhSRuJp-BLf40yqz7c',
    appId: '1:846870916054:web:5e7b6737c4f85c28861277',
    messagingSenderId: '846870916054',
    projectId: 'deconnect-app',
    authDomain: 'deconnect-app.firebaseapp.com',
    storageBucket: 'deconnect-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABJkGoo824o-a9B17HEE-2cpQPAgJqvM4',
    appId: '1:846870916054:android:c0fcc2fe5225466d861277',
    messagingSenderId: '846870916054',
    projectId: 'deconnect-app',
    storageBucket: 'deconnect-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC7X5Vtc39eJpSukHUqmul-0zFw3qQlFg',
    appId: '1:846870916054:ios:0b29853ae504f058861277',
    messagingSenderId: '846870916054',
    projectId: 'deconnect-app',
    storageBucket: 'deconnect-app.firebasestorage.app',
    iosBundleId: 'com.example.onboardingProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC7X5Vtc39eJpSukHUqmul-0zFw3qQlFg',
    appId: '1:846870916054:ios:0b29853ae504f058861277',
    messagingSenderId: '846870916054',
    projectId: 'deconnect-app',
    storageBucket: 'deconnect-app.firebasestorage.app',
    iosBundleId: 'com.example.onboardingProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASXCv9PEiuopdAjKhSRuJp-BLf40yqz7c',
    appId: '1:846870916054:web:37d0995be99f5a3e861277',
    messagingSenderId: '846870916054',
    projectId: 'deconnect-app',
    authDomain: 'deconnect-app.firebaseapp.com',
    storageBucket: 'deconnect-app.firebasestorage.app',
  );
}
